import json
import os
from typing import Dict, Any, Optional
from quiz_data import CURATED_TOPIC_DATA

def is_gemini_configured() -> bool:
    """Check if GEMINI_API_KEY environment variable is set."""
    return bool(os.environ.get("GEMINI_API_KEY", "").strip())

def generate_ai_quiz(topic_name: str) -> Dict[str, Any]:
    """
    Generate learning summary and quiz questions for a topic using Gemini API.
    Falls back gracefully to curated topic data if API key is not set or if request fails.
    """
    fallback_data = CURATED_TOPIC_DATA.get(topic_name, {
        "summary": f"Comprehensive learning guide and test questions for {topic_name}.",
        "key_points": [
            f"Core foundational principles of {topic_name}.",
            f"Practical real-world applications of {topic_name}.",
            f"Key problem-solving techniques in {topic_name}."
        ],
        "questions": []
    })

    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        return {
            **fallback_data,
            "source": "curated",
            "message": "Running in Curated Learning mode. Set GEMINI_API_KEY in your environment to unlock real-time AI quiz generation!"
        }

    try:
        from google import genai
        from google.genai import types

        client = genai.Client()

        prompt = f"""
        Generate an educational overview and an engaging 3-question multiple-choice quiz for the computer science topic: "{topic_name}".
        Provide:
        1. A clear, concise educational summary (2-3 paragraphs).
        2. 3 key takeaway bullet points.
        3. Exactly 3 multiple-choice questions with 4 distinct options each, identifying the 0-indexed correct option, and a helpful explanation.
        """

        schema = {
            "type": "OBJECT",
            "required": ["summary", "key_points", "questions"],
            "properties": {
                "summary": {"type": "STRING"},
                "key_points": {
                    "type": "ARRAY",
                    "items": {"type": "STRING"}
                },
                "questions": {
                    "type": "ARRAY",
                    "items": {
                        "type": "OBJECT",
                        "required": ["question", "options", "correct_index", "explanation"],
                        "properties": {
                            "question": {"type": "STRING"},
                            "options": {
                                "type": "ARRAY",
                                "items": {"type": "STRING"}
                            },
                            "correct_index": {"type": "INTEGER"},
                            "explanation": {"type": "STRING"}
                        }
                    }
                }
            }
        }

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_json_schema=schema,
                temperature=0.7
            )
        )

        data = json.loads(response.text)
        
        # Ensure questions have 1-based IDs for frontend mapping
        for idx, q in enumerate(data.get("questions", []), start=1):
            q["id"] = idx

        return {
            "summary": data.get("summary", fallback_data.get("summary")),
            "key_points": data.get("key_points", fallback_data.get("key_points")),
            "questions": data.get("questions", fallback_data.get("questions")),
            "source": "gemini-ai",
            "message": "✨ Freshly generated by Gemini 2.5 Flash AI!"
        }

    except Exception as e:
        print(f"Gemini API request failed ({e}), falling back to curated content.")
        return {
            **fallback_data,
            "source": "curated",
            "message": f"AI generation temporarily unavailable ({type(e).__name__}). Showing curated lesson & quiz."
        }
