import json
import os
import traceback
from typing import Dict, Any

from quiz_data import CURATED_TOPIC_DATA


def is_gemini_configured() -> bool:
    """Check if GEMINI_API_KEY environment variable is set."""
    return bool(os.environ.get("GEMINI_API_KEY", "").strip())


def generate_ai_quiz(topic_name: str) -> Dict[str, Any]:
    """Generate summary + quiz with Gemini; fall back to curated data on any failure."""
    fallback_data = CURATED_TOPIC_DATA.get(topic_name, {
        "summary": f"Comprehensive learning guide and test questions for {topic_name}.",
        "key_points": [
            f"Core foundational principles of {topic_name}.",
            f"Practical real-world applications of {topic_name}.",
            f"Key problem-solving techniques in {topic_name}.",
        ],
        "questions": [],
    })

    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        return {
            **fallback_data,
            "source": "curated",
            "message": "Running in Curated Learning mode. Set GEMINI_API_KEY to unlock AI quiz generation!",
        }

    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=api_key)

        prompt = f"""
Generate an educational overview and a 3-question multiple-choice quiz for the computer science topic: "{topic_name}".
Return ONLY valid JSON in exactly this format:
{{
  "summary": "2-3 paragraphs",
  "key_points": ["point 1", "point 2", "point 3"],
  "questions": [
    {{"question": "...", "options": ["A", "B", "C", "D"], "correct_index": 0, "explanation": "..."}}
  ]
}}
Exactly 3 questions, 4 options each. correct_index is 0-based.
"""

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.7,
            ),
        )

        data = json.loads(response.text)

        # Keep only well-formed questions (4 options, valid correct_index)
        questions = [
            q for q in data.get("questions", [])
            if len(q.get("options", [])) == 4 and 0 <= q.get("correct_index", -1) < 4
        ]
        for idx, q in enumerate(questions, start=1):
            q["id"] = idx

        return {
            "summary": data.get("summary", fallback_data.get("summary")),
            "key_points": data.get("key_points", fallback_data.get("key_points")),
            "questions": questions or fallback_data.get("questions", []),
            "source": "gemini-ai",
            "message": "✨ Freshly generated by Gemini 2.5 Flash AI!",
        }

    except Exception as e:
        traceback.print_exc()
        print(f"Gemini API request failed: {e}")
        return {
            **fallback_data,
            "source": "curated",
            "message": f"AI generation temporarily unavailable ({type(e).__name__}: {str(e)[:100]}). Showing curated lesson & quiz.",
        }